B=[
"Social Security only counts thirty five years of your working life. If you worked thirty, it does not skip the missing five. It fills them in with zeros. And for one average worker, those five zeros cost more than three thousand two hundred dollars every single year, for life. Stay until the end, because number four is the one that surprises almost everyone.",
"Welcome to The Money Backstory, where we explain retirement for Americans over fifty, using official numbers. To keep this simple, we will follow two coworkers, Frank and Mary. They earned exactly the same wages. The only difference is that Frank stopped working after thirty years, and Mary kept going for thirty five. Watch what happens to their checks.",
"Here is the plan. You will learn the five things that decide your Social Security check. One, the thirty five year rule. Two, the formula that turns your salary into a monthly amount. Three, what your claiming age really does to that amount. Four, what happens if you keep working while you collect. And five, what your spouse can get. At the end, we will answer the question everybody asks: will the money still be there?",
"Number one: the thirty five year rule. To qualify for retirement benefits, you need forty credits, which usually means about ten years of work. But the size of your check depends on something else. The Social Security Administration adjusts your old salaries to today's wage levels, and then picks your highest thirty five years. Your last salary does not matter. Your best thirty five years do.",
"Now here is the catch. If you have fewer than thirty five years of earnings, the missing years are counted as zero. Not skipped. Zero. Those zeros get averaged in with everything else, and they drag your monthly average down. Many people who stayed home to raise kids, care for a parent, or lost a job never realize this is happening.",
"Let's see what that does to Frank and Mary. Say both earn the equivalent of about seventy two thousand dollars a year in today's wages. Mary has thirty five years, so her average is six thousand dollars a month. Frank has only thirty years, so five zero years pull his average down to about five thousand one hundred forty three dollars a month.",
"That gap looks small, but watch the final check. Mary's full benefit comes out to two thousand six hundred sixty five dollars and eighty cents a month. Frank's is only two thousand three hundred ninety one dollars and fifty cents. That is two hundred seventy four dollars less every month, about three thousand two hundred ninety two dollars a year. Over twenty years, before any raises, that is more than sixty five thousand dollars.",
"So what can you do about it? If you are still working and you have fewer than thirty five years, every extra year of work replaces one of those zeros. Even a modest year is better than a zero. And you can check your own record for free, inside your my Social Security account at ssa dot gov. Look for missing years, because mistakes do happen.",
"Number two: the formula. Once Social Security has your best thirty five years, it adds them up and divides by four hundred twenty months. That gives what it calls your average indexed monthly earnings. Then it runs that number through a formula with three slices, and this is where things get interesting.",
"For people turning sixty two in twenty twenty six, the formula works like this. You get ninety percent of the first one thousand two hundred eighty six dollars. Then thirty two percent of everything between one thousand two hundred eighty six and seven thousand seven hundred forty nine dollars. And only fifteen percent of anything above that.",
"Let's run Mary's six thousand dollars through it. Ninety percent of the first one thousand two hundred eighty six is one thousand one hundred fifty seven dollars and forty cents. Then thirty two percent of the remaining four thousand seven hundred fourteen is one thousand five hundred eight dollars and forty eight cents. Add them together, round down, and you get two thousand six hundred sixty five dollars and eighty cents a month.",
"Notice what this formula does. It is built to help lower earners more. Someone averaging three thousand dollars a month gets back about fifty seven percent of it. Mary, at six thousand, gets back about forty four percent. And someone at ten thousand dollars gets back only about thirty six percent. The more you earn, the smaller the share Social Security replaces.",
"There is also a ceiling. In twenty twenty six, Social Security only counts earnings up to one hundred eighty four thousand five hundred dollars a year. Anything above that does not raise your benefit. That is why even the highest earners hit a maximum, which for someone at full retirement age in twenty twenty six is four thousand one hundred fifty two dollars a month.",
"Number three: your claiming age. Everything we just calculated is your full benefit, the amount you get at full retirement age. For anyone born in nineteen sixty or later, that age is sixty seven. Claim earlier and the check shrinks. Claim later and it grows. And the change is permanent.",
"At sixty two, you get seventy percent of your full amount. At sixty three, seventy five. At sixty four, eighty. At sixty five, about eighty seven. At sixty six, about ninety three. And at sixty seven, one hundred percent. The reduction is just over half a percent for every month you claim early during the first three years, and a little less after that.",
"Now the other direction. Wait past sixty seven, and Social Security adds delayed retirement credits of eight percent for every year. That is one hundred eight percent at sixty eight, one hundred sixteen percent at sixty nine, and one hundred twenty four percent at seventy. After seventy, waiting adds nothing, so there is no reason to delay beyond that.",
"Put dollars on it. Mary's full benefit is two thousand six hundred sixty five dollars and eighty cents. If she claimed at sixty two, she would get about one thousand eight hundred sixty six dollars. If she waits until seventy, about three thousand three hundred six dollars. That is more than seventeen thousand dollars more every year, for the same career.",
"And there is a bonus. Every year, Social Security adds a cost of living increase. In twenty twenty six it was two point eight percent, which lifted the average retired worker's check to two thousand seventy one dollars a month. But a raise is a percentage of your check. On the smaller early check, it is about fifty two dollars. On the bigger late check, about ninety three dollars. The gap keeps growing.",
"Now, number four, the one I promised would surprise you. What if you claim early but you are still working? Before full retirement age, Social Security has an earnings limit. In twenty twenty six, it is twenty four thousand four hundred eighty dollars. For every two dollars you earn above that, they withhold one dollar of your benefits.",
"Say Frank claims at sixty two and keeps a job paying forty thousand dollars. That is fifteen thousand five hundred twenty dollars above the limit. Half of it, seven thousand seven hundred sixty dollars, gets withheld. At his benefit of about one thousand six hundred seventy four dollars a month, that is more than four months of checks that simply do not arrive.",
"It sounds like that money is gone forever. It is not, and this is the part almost nobody knows. When you reach full retirement age, Social Security recalculates your benefit and gives you credit for the months that were withheld. So the money is not lost. It comes back as a higher monthly check, for the rest of your life.",
"Two more details. In the year you reach full retirement age, the limit jumps to sixty five thousand one hundred sixty dollars, and only one dollar is withheld for every three you earn above it. Once you reach full retirement age, there is no limit at all. And only paychecks and self employment income count. Pensions, investment income, and withdrawals from your four oh one k do not.",
"Number five: your spouse. If you are married, your spouse may be able to collect a benefit based on your record instead of their own. At their own full retirement age, it can be up to fifty percent of your full benefit, but only after you have filed for yours. With Mary's full benefit, a spouse with little work history could get up to about one thousand three hundred thirty three dollars.",
"But timing matters here too. If that spouse claims three years early, the benefit drops to thirty seven and a half percent of the worker's full amount, instead of fifty. And unlike your own benefit, a spousal benefit does not grow if you wait past full retirement age. If you are divorced, you may still qualify, as long as the marriage lasted at least ten years.",
"Now the part nobody wants to think about: survivor benefits. When one spouse dies, the survivor does not keep both checks. The survivor keeps the larger one, and the smaller one disappears. A widow or widower can start as early as sixty, at about seventy one and a half percent of the deceased spouse's benefit. At full retirement age, it can be one hundred percent.",
"This is why the higher earner's claiming age matters so much for couples. If Mary waits until seventy, her check is about three thousand three hundred six dollars, and that is the amount her surviving spouse can keep for life. The delay is not only for her. It is insurance for whoever lives longer.",
"Now the question everyone asks. Will Social Security even be there? The Trustees report released in June of twenty twenty six says the retirement trust fund can pay full scheduled benefits until the last quarter of twenty thirty two. Both trust funds combined last until twenty thirty four. These are official projections from the people who run the program.",
"But notice what they did not say. After that date, the program does not go to zero. Payroll taxes keep coming in. The trustees estimate that the retirement fund could still pay about seventy eight percent of scheduled benefits, and the combined funds about eighty three percent. Mary's check of two thousand six hundred sixty five dollars would become about two thousand seventy nine dollars.",
"Could Congress fix it? It has before. In nineteen eighty three, lawmakers changed the rules to keep the program going. Nobody can promise what happens this time, and this video is education, not advice. But a smart way to plan is simple: look at your own number, then test what happens if it were about a fifth smaller.",
"Let's recap the five things. One: only your best thirty five years count, and missing years are zeros. Two: the formula gives back a bigger slice of your income if you earn less. Three: claiming at sixty two means seventy percent, waiting until seventy means one hundred twenty four. Four: earnings withheld are not lost, they come back later. Five: spouses and survivors have their own rules.",
"If this helped, tap like and subscribe to The Money Backstory, so you do not miss the next one. And if you want to see the exact math behind claiming at sixty two versus seventy, that video is right on your screen now. See you there.",
]
if __name__=="__main__":
    tot=0
    for i,b in enumerate(B,1):
        tot+=len(b); print(i,len(b),round(len(b)/14.5,1))
    print("N",len(B),"chars",tot,"sec@14.5",round(tot/14.5),"min",round(tot/14.5/60,2))
    import re
    print([i+1 for i,b in enumerate(B) if re.search(r'\d',b)])
